version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always
    environment:
      - INFLUXDB_DB=particulaInfluxDB
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - influxdb
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    env_file:
      - .env
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  backend:
    image: https://github.com/vives-projectwerk-2-2020/back-end.git#develop
    restart: always
    env_file:
      - .env
    ports:
      - 8080:3000
  lorawan: 
    image: https://github.com/vives-projectwerk-2-2020/lorawan-listener.git#dev
    restart: always
    env_file:
      - .env
    ports: 
      - 5000
  frontend:
    image: https://github.com/vives-projectwerk-2-2020/Frontend.git#develop
    restart: always
    ports:
      - 80:80
volumes:
  influxdb-storage:
  grafana-storage:
  db:
