version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always
    environment:
      - INFLUXDB_DB=particulaInfluxDB
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  backend:
    build: https://github.com/vives-projectwerk-2-2020/back-end.git#develop
    restart: always
    ports:
      - 3000:3000
    command: php -S 0.0.0.0:3000
  lorawan: 
    build: https://github.com/vives-projectwerk-2-2020/lorawan-listener.git#dev
    restart: always
    environment: 
      - APP_ID=maximva-loratest
      - ACCESSKEY=ttn-account-v2.XAZxgVSlF8PG9Y_njU_-3OnDWGsQvuqyyyAcb4SWDvk
      - REAL_TIME_IP=172.16.101.26
      - INFLUX_IP=192.168.99.100
      - INFLUX_PORT=8086
    ports: 
      - 5000:5000
  frontend:
    build: https://github.com/vives-projectwerk-2-2020/Frontend-Hello-World.git
    restart: always
    ports:
      - 8080:80
volumes:
  influxdb-storage:
  grafana-storage:
  db:
  adminer: