version: '3'

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # - "--certificatesResolvers.le.acme.email=<YOUR_EMAIL>"
      - "--certificatesResolvers.le.acme.storage=acme.json"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    networks:
      - web
    labels:
      # Redirect all HTTP to HTTPS permanently
      - traefik.enable=true
      - traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http_catchall.entrypoints=web
      - traefik.http.routers.http_catchall.middlewares=https_redirect
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true

      - traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.middlewares.api.compress=true
      - traefik.http.routers.api.service=api@internal
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=arno:$$apr1$$cUz7.Cx4$$dxuosccFFo5gC1URBCZwx."
      - "traefik.http.middlewares.auth.basicauth.headerField=X-WebAuth-User"
      - "traefik.http.middlewares.auth.basicauth.removeheader=true"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always
    env_file:
      - .env
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - influxdb
    restart: always
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    env_file:
      - .env
    networks:
      - web
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=le
      - traefik.http.middlewares.grafana.compress=true
      - traefik.http.routers.grafana.middlewares=grafana@docker

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - backend

  backend:
    image: docker.pkg.github.com/vives-projectwerk-2-2020/back-end/particula-back-end-dev
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - 8080:3000
    networks:
      - backend

  lorawan: 
    image: docker.pkg.github.com/vives-projectwerk-2-2020/lorawan-listener/particula-lorawan-listener-dev
    container_name: lorawan
    restart: always
    env_file:
      - .env
    networks:
      - backend

  frontend:
    image: docker.pkg.github.com/vives-projectwerk-2-2020/frontend/particula-frontend-dev
    container_name: frontend
    restart: always
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=le
      - traefik.http.middlewares.frontend.compress=true
      - traefik.http.routers.frontend.middlewares=frontend@docker

networks:
  web:
    external: true
  backend:
    external: false

volumes:
  influxdb-storage:
  grafana-storage:
  db: