version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always
    environment:
      - INFLUXDB_DB=particulaInfluxDB
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  backend:
    build: https://github.com/vives-projectwerk-2-2020/back-end.git
    restart: always
    ports:
      - 3000:3000
    command: php -S 0.0.0.0:3000
  lorawan: 
    build: https://github.com/vives-projectwerk-2-2020/lorawan-listener.git
    restart: always
    env_file:
      - .env
    ports: 
      - 5000:5000
  frontend:
    build: https://github.com/vives-projectwerk-2-2020/FrontendApplication
    restart: always
    ports:
      - 8080:80
volumes:
  influxdb-storage:
  grafana-storage:
  db:
